export const PHRASE_CATEGORIES: { key: string; icon: string; en: string; ja: string }[] = [
  { key: 'greetings',      icon: '1F44B', en: 'Greetings',             ja: '挨拶' },
  { key: 'introduction',   icon: '1F464', en: 'Introduction',           ja: '自己紹介' },
  { key: 'daily_life',     icon: '1F4AC', en: 'Daily Life',             ja: '日常会話' },
  { key: 'gratitude',      icon: '1F64F', en: 'Thanks & Apologies',     ja: '感謝・謝罪' },
  { key: 'compliments',    icon: '2728',  en: 'Compliments',            ja: '褒め言葉' },
  { key: 'questions',      icon: '2753',  en: 'Questions',              ja: '質問' },
  { key: 'emotions',       icon: '1F60A', en: 'Emotions',               ja: '感情・気持ち' },
  { key: 'family',         icon: '1F46A', en: 'Family',                 ja: '家族' },
  { key: 'social',         icon: '1F91D', en: 'Social',                 ja: '社交・付き合い' },
  { key: 'romance',        icon: '1F495', en: 'Romance',                ja: '恋愛' },
  { key: 'home',           icon: '1F3E0', en: 'Home',                   ja: '家・住まい' },
  { key: 'food',           icon: '1F37D', en: 'Food & Dining',          ja: '食事' },
  { key: 'food_local',     icon: '1F35A', en: 'Local Food',             ja: '地元料理' },
  { key: 'shopping',       icon: '1F6CD', en: 'Shopping',               ja: '買い物' },
  { key: 'money',          icon: '1F4B0', en: 'Money',                  ja: 'お金' },
  { key: 'transport',      icon: '1F68C', en: 'Transport',              ja: '交通' },
  { key: 'travel',         icon: '1F9F3', en: 'Travel',                 ja: '旅行' },
  { key: 'accommodation',  icon: '1F3E8', en: 'Accommodation',          ja: '宿泊' },
  { key: 'health',         icon: '1F3E5', en: 'Health & Medical',       ja: '健康・医療' },
  { key: 'emergency',      icon: '26A0',  en: 'Emergency',              ja: '緊急' },
  { key: 'time',           icon: '23F0',  en: 'Time & Schedule',        ja: '時間・日程' },
  { key: 'weather',        icon: '1F326', en: 'Weather',                ja: '天気' },
  { key: 'nature',         icon: '1F33F', en: 'Nature',                 ja: '自然' },
  { key: 'school',         icon: '1F4DA', en: 'School & Study',         ja: '学校・勉強' },
  { key: 'work',           icon: '1F4BC', en: 'Work',                   ja: '仕事' },
  { key: 'phone',          icon: '1F4F1', en: 'Phone & Messages',       ja: '電話・メッセージ' },
  { key: 'sports',         icon: '26BD',  en: 'Sports & Games',         ja: 'スポーツ・遊び' },
  { key: 'celebrations',   icon: '1F389', en: 'Celebrations',           ja: 'お祝い・行事' },
  { key: 'religion',       icon: '1F64F', en: 'Religion & Faith',       ja: '宗教・信仰' },
  { key: 'slang',          icon: '1F525', en: 'Slang & Expressions',    ja: 'スラング・表現' },
]
