export type SubCategory = { key: string; en: string; ja: string }

export type WordCategoryGroup = {
  key: string
  en: string
  ja: string
  icon: string
  subCategories: SubCategory[]
}

export const WORD_CATEGORY_GROUPS: WordCategoryGroup[] = [
  {
    key: 'people', en: 'People & Relationships', ja: '人・関係', icon: '1F46A',
    subCategories: [
      { key: 'family_core',        en: 'Core Family',        ja: '家族' },
      { key: 'family_extended',    en: 'Extended Family',    ja: '親戚' },
      { key: 'life_stages',        en: 'Life Stages',        ja: '人生の段階' },
      { key: 'social_titles',      en: 'Titles & Honorifics',ja: '敬称・役職' },
      { key: 'professions_1',      en: 'Professions I',      ja: '職業①' },
      { key: 'professions_2',      en: 'Professions II',     ja: '職業②' },
      { key: 'social_groups',      en: 'Social Groups',      ja: '社会集団' },
    ],
  },
  {
    key: 'body', en: 'Body & Health', ja: 'からだ・健康', icon: '1F4AA',
    subCategories: [
      { key: 'body_external',      en: 'External Body',      ja: '体の外側' },
      { key: 'body_internal',      en: 'Internal Organs',    ja: '体の内側' },
      { key: 'body_senses',        en: 'Senses',             ja: '五感' },
      { key: 'health_illness',     en: 'Illness',            ja: '病気・症状' },
      { key: 'health_treatment',   en: 'Treatment',          ja: '治療・薬' },
      { key: 'health_wellness',    en: 'Wellness',           ja: '健康・養生' },
    ],
  },
  {
    key: 'emotions', en: 'Emotions & Mind', ja: '感情・心', icon: '1F60A',
    subCategories: [
      { key: 'emotions_positive',  en: 'Positive Emotions',  ja: 'ポジティブな感情' },
      { key: 'emotions_negative',  en: 'Negative Emotions',  ja: 'ネガティブな感情' },
      { key: 'emotions_complex',   en: 'Complex Emotions',   ja: '複雑な感情' },
      { key: 'mental_states',      en: 'Mental States',      ja: '心理状態' },
      { key: 'personality_traits', en: 'Personality',        ja: '性格・特徴' },
    ],
  },
  {
    key: 'animals', en: 'Animals', ja: '動物', icon: '1F43E',
    subCategories: [
      { key: 'animals_mammals',    en: 'Mammals',            ja: '哺乳類' },
      { key: 'animals_birds',      en: 'Birds',              ja: '鳥類' },
      { key: 'animals_sea_fish',   en: 'Sea & Fish',         ja: '海の生き物・魚' },
      { key: 'animals_shellfish',  en: 'Shellfish',          ja: '貝・甲殻類' },
      { key: 'animals_reptiles',   en: 'Reptiles',           ja: '爬虫類・両生類' },
      { key: 'animals_insects',    en: 'Insects',            ja: '昆虫' },
      { key: 'animals_domestic',   en: 'Farm Animals',       ja: '家畜' },
    ],
  },
  {
    key: 'plants', en: 'Plants & Nature', ja: '植物・自然', icon: '1F33F',
    subCategories: [
      { key: 'plants_trees',         en: 'Trees',            ja: '木・樹木' },
      { key: 'plants_shrubs_vines',  en: 'Shrubs & Vines',   ja: '低木・つる植物' },
      { key: 'plants_flowers',       en: 'Flowers',          ja: '花' },
      { key: 'plants_vegetables',    en: 'Vegetables',       ja: '野菜' },
      { key: 'plants_fruits',        en: 'Fruits',           ja: '果物' },
      { key: 'plants_grains_root',   en: 'Grains & Root Crops', ja: '穀物・根菜' },
      { key: 'plants_herbs_spices',  en: 'Herbs & Spices',   ja: 'ハーブ・スパイス' },
      { key: 'plants_medicinal',     en: 'Medicinal Plants', ja: '薬草' },
      { key: 'plants_water',         en: 'Aquatic Plants',   ja: '水生植物' },
    ],
  },
  {
    key: 'weather', en: 'Weather & Environment', ja: '天気・環境', icon: '26A1',
    subCategories: [
      { key: 'weather_phenomena',    en: 'Weather',          ja: '天気・気象' },
      { key: 'weather_seasons',      en: 'Seasons',          ja: '季節' },
      { key: 'geography_landforms',  en: 'Landforms',        ja: '地形' },
      { key: 'geography_coastal',    en: 'Coastal Geography',ja: '海岸・島' },
      { key: 'natural_materials',    en: 'Natural Materials',ja: '自然素材' },
      { key: 'natural_phenomena',    en: 'Natural Phenomena',ja: '自然現象' },
    ],
  },
  {
    key: 'food', en: 'Food & Drink', ja: '食べ物・飲み物', icon: '1F37D',
    subCategories: [
      { key: 'food_rice_staples',    en: 'Rice & Staples',   ja: '米・主食' },
      { key: 'food_meat_dishes',     en: 'Meat Dishes',      ja: '肉料理' },
      { key: 'food_seafood_dishes',  en: 'Seafood Dishes',   ja: '魚介料理' },
      { key: 'food_veg_dishes',      en: 'Vegetable Dishes', ja: '野菜料理' },
      { key: 'food_soups_stews',     en: 'Soups & Stews',    ja: 'スープ・煮込み' },
      { key: 'food_street_food',     en: 'Street Food',      ja: '屋台・スナック' },
      { key: 'food_desserts',        en: 'Desserts',         ja: 'デザート・お菓子' },
      { key: 'food_fermented',       en: 'Fermented Foods',  ja: '発酵食品' },
      { key: 'food_ingredients',     en: 'Ingredients',      ja: '調味料・材料' },
      { key: 'drinks_traditional',   en: 'Traditional Drinks',ja: '伝統的な飲み物' },
      { key: 'drinks_modern',        en: 'Modern Drinks',    ja: '現代的な飲み物' },
    ],
  },
  {
    key: 'household', en: 'Household & Tools', ja: '家・道具', icon: '1F3E0',
    subCategories: [
      { key: 'household_furniture',  en: 'Furniture',        ja: '家具' },
      { key: 'household_kitchen',    en: 'Kitchen',          ja: 'キッチン用品' },
      { key: 'household_cleaning',   en: 'Cleaning',         ja: '掃除用品' },
      { key: 'household_storage',    en: 'Storage',          ja: '収納' },
      { key: 'tools_farming',        en: 'Farming Tools',    ja: '農具' },
      { key: 'tools_fishing',        en: 'Fishing Tools',    ja: '漁具' },
      { key: 'tools_construction',   en: 'Construction',     ja: '建設・工具' },
      { key: 'tools_crafts',         en: 'Craft Tools',      ja: '工芸・手工具' },
    ],
  },
  {
    key: 'clothing', en: 'Clothing & Transport', ja: '衣服・交通', icon: '1F3C3',
    subCategories: [
      { key: 'clothing_traditional', en: 'Traditional Clothing', ja: '伝統衣装' },
      { key: 'clothing_everyday',    en: 'Everyday Clothing',    ja: '日常の衣服' },
      { key: 'clothing_accessories', en: 'Accessories',          ja: 'アクセサリー' },
      { key: 'transport_land',       en: 'Land Transport',       ja: '陸上交通' },
      { key: 'transport_sea',        en: 'Sea Transport',        ja: '海上交通' },
      { key: 'transport_air',        en: 'Air Transport',        ja: '航空' },
    ],
  },
  {
    key: 'places', en: 'Places & Time', ja: '場所・時間', icon: '23F0',
    subCategories: [
      { key: 'places_home',          en: 'Home',             ja: '家・住居' },
      { key: 'places_community',     en: 'Community',        ja: '地域・コミュニティ' },
      { key: 'places_nature_spots',  en: 'Nature Spots',     ja: '自然の場所' },
      { key: 'places_commercial',    en: 'Commercial Places',ja: '商業施設' },
      { key: 'places_government',    en: 'Government Places',ja: '公共施設' },
      { key: 'time_clock',           en: 'Clock & Time',     ja: '時計・時刻' },
      { key: 'time_days_weeks',      en: 'Days & Weeks',     ja: '曜日・週' },
      { key: 'time_months_years',    en: 'Months & Years',   ja: '月・年' },
      { key: 'time_relative',        en: 'Relative Time',    ja: '相対的な時間' },
      { key: 'time_frequency',       en: 'Frequency',        ja: '頻度' },
    ],
  },
  {
    key: 'numbers', en: 'Numbers & Quantities', ja: '数・量', icon: '1F522',
    subCategories: [
      { key: 'numbers_cardinal',     en: 'Cardinal Numbers', ja: '基数' },
      { key: 'numbers_ordinal',      en: 'Ordinal Numbers',  ja: '序数' },
      { key: 'quantities_measures',  en: 'Quantities & Measures', ja: '数量・単位' },
    ],
  },
  {
    key: 'culture', en: 'Culture & Society', ja: '文化・社会', icon: '1F3A8',
    subCategories: [
      { key: 'greetings',            en: 'Greetings',        ja: '挨拶' },
      { key: 'religion_christian',   en: 'Christianity',     ja: 'キリスト教' },
      { key: 'religion_traditional', en: 'Traditional Beliefs', ja: '伝統的信仰' },
      { key: 'education_school',     en: 'Education',        ja: '教育・学校' },
      { key: 'government_law',       en: 'Government & Law', ja: '政府・法律' },
      { key: 'business_commerce',    en: 'Business',         ja: 'ビジネス・商業' },
      { key: 'technology_general',   en: 'Technology',       ja: 'テクノロジー' },
      { key: 'sports_local',         en: 'Sports & Leisure', ja: 'スポーツ・娯楽' },
      { key: 'music_arts',           en: 'Music & Arts',     ja: '音楽・芸術' },
      { key: 'festivals_events',     en: 'Festivals & Events',ja: '祭り・行事' },
      { key: 'superstitions',        en: 'Superstitions',    ja: '迷信・伝説' },
      { key: 'proverbs_idioms',      en: 'Proverbs & Idioms',ja: 'ことわざ・慣用句' },
      { key: 'sea_culture',          en: 'Sea Culture',      ja: '海の文化' },
      { key: 'agriculture_culture',  en: 'Agriculture',      ja: '農業文化' },
      { key: 'disaster_terms',       en: 'Disasters',        ja: '災害・緊急' },
      { key: 'environment_ecology',  en: 'Environment',      ja: '環境・エコロジー' },
    ],
  },
  {
    key: 'describing', en: 'How Things Are', ja: '様子・ありさま', icon: '2728',
    subCategories: [
      { key: 'adj_size_shape',       en: 'Size & Shape',     ja: '大きさ・形' },
      { key: 'adj_colors',           en: 'Colors',           ja: '色' },
      { key: 'adj_texture',          en: 'Texture',          ja: '質感・手触り' },
      { key: 'adj_taste_smell',      en: 'Taste & Smell',    ja: '味・匂い' },
      { key: 'adj_temperature',      en: 'Temperature',      ja: '温度' },
      { key: 'adj_physical_state',   en: 'Physical State',   ja: '物理的状態' },
      { key: 'adj_character_good',   en: 'Good Character',   ja: '良い性格' },
      { key: 'adj_character_neg',    en: 'Bad Character',    ja: '悪い性格' },
      { key: 'adj_intelligence',     en: 'Intelligence',     ja: '知性・賢さ' },
      { key: 'adj_beauty',           en: 'Beauty',           ja: '美しさ' },
      { key: 'adj_age',              en: 'Age',              ja: '年齢・新旧' },
      { key: 'adj_status',           en: 'Status',           ja: '状態・地位' },
    ],
  },
  {
    key: 'doing', en: 'Things People Do', ja: '動き・活動', icon: '1F3C3',
    subCategories: [
      { key: 'verbs_walking',        en: 'Walking',          ja: '歩く・移動' },
      { key: 'verbs_transit',        en: 'Transit',          ja: '乗り物での移動' },
      { key: 'verbs_hands',          en: 'Hand Actions',     ja: '手の動作' },
      { key: 'verbs_head_face',      en: 'Head & Face',      ja: '頭・顔の動作' },
      { key: 'verbs_body_motion',    en: 'Body Motion',      ja: '体の動き' },
      { key: 'verbs_speaking',       en: 'Speaking',         ja: '話す・言う' },
      { key: 'verbs_written',        en: 'Writing',          ja: '書く' },
      { key: 'verbs_expression',     en: 'Expression',       ja: '表現する' },
      { key: 'verbs_social_comm',    en: 'Social Communication', ja: 'コミュニケーション' },
      { key: 'verbs_cooking',        en: 'Cooking',          ja: '料理する' },
      { key: 'verbs_farming',        en: 'Farming',          ja: '農作業' },
      { key: 'verbs_fishing',        en: 'Fishing',          ja: '漁・釣り' },
      { key: 'verbs_building',       en: 'Building',         ja: '建てる・作る' },
      { key: 'verbs_trade',          en: 'Trade',            ja: '取引・売買' },
      { key: 'verbs_cleaning',       en: 'Cleaning',         ja: '掃除・洗う' },
      { key: 'verbs_repair',         en: 'Repair',           ja: '修理・直す' },
      { key: 'verbs_caring',         en: 'Caring',           ja: '世話・介護' },
      { key: 'verbs_change',         en: 'Change',           ja: '変える・変わる' },
      { key: 'verbs_start_stop',     en: 'Start & Stop',     ja: '始める・止める' },
      { key: 'verbs_exist_have',     en: 'Exist & Have',     ja: 'ある・持つ' },
      { key: 'verbs_become',         en: 'Become',           ja: 'なる・変化' },
    ],
  },
  {
    key: 'connecting', en: 'Connecting Words', ja: 'つなぎ・表現', icon: '1F4DD',
    subCategories: [
      { key: 'adverbs_manner',       en: 'How (Manner)',     ja: 'どのように' },
      { key: 'adverbs_degree',       en: 'How Much',         ja: 'どのくらい' },
      { key: 'adverbs_place',        en: 'Where',            ja: 'どこ・場所' },
      { key: 'adverbs_time',         en: 'When',             ja: 'いつ・時' },
      { key: 'adverbs_affirmation',  en: 'Nuance Words',     ja: 'ニュアンスのことば' },
      { key: 'pronouns_personal',    en: 'I, You, We',       ja: '私・あなた・私たち' },
      { key: 'pronouns_demonst',     en: 'This & That',      ja: 'これ・それ・あれ' },
      { key: 'question_words',       en: 'Question Words',   ja: '疑問のことば' },
      { key: 'prepositions',         en: 'Position Words',   ja: '位置・方向のことば' },
      { key: 'conjunctions',         en: 'Linking Words',    ja: 'つなぐことば' },
      { key: 'discourse_particles',  en: 'Filler Words',     ja: '話しことばの表現' },
      { key: 'interjections',        en: 'Exclamations',     ja: '感嘆・掛け声' },
    ],
  },
]
